USE jw_group05_db;

CREATE TABLE BROKERAGE (
	PAYOR_ID VARCHAR(10) PRIMARY KEY,
    NAME     VARCHAR(20),
    ADDRESS  VARCHAR(30),
    COMMISSION DECIMAL(3,2),
    BROKERAGE_TYPE VARCHAR(3),
    INDEPENDENT_CAPTIVE VARCHAR(1)
);
