USE jw_group05_db;

CREATE TABLE IF NOT EXISTS DEPOSIT(
    TRANSACTION_ID VARCHAR(20) NOT NULL,
    AMOUNT_DEPOSIT INT NOT NULL,
    ACCOUNT_NUM VARCHAR(1) NOT NULL,
    PRIMARY KEY(TRANSACTION_ID),
    FOREIGN KEY(TRANSACTION_ID)
        REFERENCES TRANSACTION(TRANSACTION_ID)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    FOREIGN KEY(ACCOUNT_NUM)
        REFERENCES ACCOUNT(ACCOUNT_NUM)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);
