USE jw_group05_db;

CREATE TABLE INDIVIDUAL (
    ACCOUNT_TYPE VARCHAR(3) PRIMARY KEY,
    TAXABLE_NOW VARCHAR(1),
    PROFIT_TAX DECIMAL(3,2),
    FOREIGN KEY(ACCOUNT_TYPE) REFERENCES ACCOUNT(ACCOUNT_TYPE)
);
