CREATE TABLE INVEST_HISTORY(
    INVESTMENT_ID VARCHAR(20) NOT NULL,
    INVEST_DATE TIMESTAMP,
    PRICE INT,
    DIVIDEND FLOAT(3, 1),
    TICKER CHAR(3),
    UNITS INT,
    PRIMARY KEY(INVESTMENT_ID),
    FOREIGN KEY(INVESTMENT_ID)
        REFERENCES INVESTMENT(INVESTMENT_ID)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);