USE jw_group05_db;

CREATE TABLE IF NOT EXISTS INVEST_SECTORS(
    INVESTMENT_ID VARCHAR(20) NOT NULL,
    SECTOR_ID VARCHAR(1) NOT NULL,
    PRIMARY KEY(INVESTMENT_ID, SECTOR_ID),
    FOREIGN KEY (INVESTMENT_ID) 
        REFERENCES INVESTMENT(INVESTMENT.INVESTMENT_ID)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (SECTOR_ID) 
        REFERENCES SECTOR(SECTOR.SECTOR_ID)
        ON UPDATE CASCADE ON DELETE RESTRICT,
);
