USE jw_group05_db;

CREATE TABLE IF NOT EXISTS INVESTMENT(
    INVESTMENT_ID VARCHAR(20),
    TRANSACTION_ID VARCHAR (20),
    ACCOUNT_NUM VARCHAR(1),
    PRIMARY KEY (INVESTMENT_ID),
    FOREIGN KEY (TRANSACTION_ID)
        REFERENCES TRANSACTION(TRANSACTION_ID)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    FOREIGN KEY (ACCOUNT_NUM)
        REFERENCES ACCOUNT(ACCOUNT_NUM)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);
