CREATE TABLE INVEST_HISTORY(
    INVESTMENT_ID VARCHAR(3),
    INVEST_DATE TIMESTAMP,
    PRICE UNSIGNED MEDIUM INT,
    DIVIDEND FLOAT(1, 3),
    TICKER CHAR(3)
    UNITS UNSIGNED INT,
    PRIMARY KEY(INVESTMENT_ID)
);