USE jw_group05_db;

CREATE TABLE IRA (
    ACCOUNT_TYPE VARCHAR(3) PRIMARY KEY,
    DEPOSIT_CAP INTEGER UNSIGNED,
    TAX_UPON_WITHDRAWL DECIMAL(3,2),
    FOREIGN KEY(ACCOUNT_TYPE) REFERENCES ACCOUNT(ACCOUNT_TYPE)
);
