USE jw_group05_db;

CREATE TABLE IF NOT EXISTS SECTOR (
    # ATTRIBUTE, TYPE, IF REQUIRED NOT NULL, AUTOINCREMENT IF PK
    SECTOR_ID VARCHAR(1) NOT NULL,
    SECTOR_NAME VARCHAR(30) NOT NULL,
    TAXABLE FLOAT(1) NOT NULL,
    PRIMARY KEY (SECTOR_ID)
);
