/* TRANSACTION_2
	2.	Create an IRA account
		A. CREATE ACCOUNT
        B. EXTEND ACCOUNT TO IRA 
		CONSIDERATIONS: DEPOSIT CAP TRIGGER, FORMAT OF ADDRESSES (STRINGS INSTEAD?)
*/
START TRANSACTION;
INSERT INTO ACCOUNT VALUES(12345, 321, 0.00, 'JANE/DOE', 'IRA');
INSERT INTO IRA VALUES(321, 1000000, 0.10);
COMMIT;