/* TRANSACTION_8
Purchase 50 shares of AMZN stock in your IRA on 9/1/20 */

SET SQL_SAFE_UPDATES = 0;
SET autocommit = 0;

START TRANSACTION; 
SET @balance = (SELECT BALANCE FROM ACCOUNT WHERE ACCOUNT_NUM = 321);
SET @purch_date = '2020-09-01';
SET @units = 50;
SET @price = 150;

INSERT INTO TRANSACTION VALUES(7, 321, @balance - (@units * @price), @purch_date, 'PUR');
INSERT INTO INVESTMENT VALUES(4, 7, 321);
INSERT INTO PURCHASE VALUES(7, 4, 321);

INSERT INTO INVEST_HISTORY VALUES(4, @purch_date, @price, 0, 'AMZN', @units);
INSERT INTO SECTOR VALUES('T2', 'AMZN', 'Y');
INSERT INTO INVEST_SECTORS VALUES(2, 'T2');

UPDATE ACCOUNT
SET BALANCE = BALANCE - (@units * @price)
WHERE ACCOUNT_NUM = 321;
INSERT INTO ACCT_HISTORY VALUES(7, 321, @purch_date, @balance - (@units * @price));

COMMIT;


#ROLLBACK; #MATCH WITH SET AUTOCOMMIT = 0;